version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_tennis:latest
    ports:
      - "8000:8000"
    volumes:
      - ./app_tennis:/app
    environment:
      # - DATABASE_HOST=${DB_HOST}
      # - DATABASE_NAME=${DB_NAME}
      # - DATABASE_USER=${DB_USER}
      # - DATABASE_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env
  

  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql  # Mount a named volume for MySQL data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - django